const data = {
  products: [
    {
      name: "Lacoste Casual White",
      category: "Shirts",
      image: "/images/p7.jpg",
      price: 275,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.6,
      numReviews: 27,
      description: "high quality product",
      show: false,
    },
    {
      name: "Adidas Cool Jacket",
      category: "Shirts",
      image: "/images/p8.jpg",
      price: 320,
      countInStock: 9,
      brand: "Adidas",
      rating: 4.9,
      numReviews: 11,
      description: "high quality product",
      show: false,
    },
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      show: false,
    },
    {
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
      show: false,
    },
    {
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
      show: false,
    },

    {
      name: "Reebok solid Casual Shirt ",
      category: "Shirts",
      image: "/images/p9.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
      show: true,
    },
    {
      name: "Nike Black Jacket",
      category: "Shirts",
      image: "/images/p10.jpg",
      price: 250,
      countInStock: 5,
      brand: "Nike",
      rating: 4.2,
      numReviews: 7,
      description: "high quality product",
      show: false,
    },
    {
      name: "Reebok Training Shirt",
      category: "Shirts",
      image: "/images/p11.jpg",
      price: 205,
      countInStock: 15,
      brand: "Reebok",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
      show: false,
    },
    {
      name: "Adidas Sea Slim T-shirt",
      category: "Shirts",
      image: "/images/p12.jpg",
      price: 220,
      countInStock: 7,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 13,
      description: "high quality product",
      show: true,
    },
    {
      name: "Lacoste Blue Casual",
      category: "Shirts",
      image: "/images/p13.jpg",
      price: 120,
      countInStock: 10,
      brand: "Lacoste",
      rating: 4.0,
      numReviews: 12,
      description: "high quality product",
      show: false,
    },

    {
      name: "Adidas Black Coat",
      category: "Shirts",
      image: "/images/p15.jpg",
      price: 220,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.8,
      numReviews: 13,
      description: "high quality product",
      show: false,
    },
    {
      name: "Lacoste Party Suit ",
      category: "Shirts",
      image: "/images/p14.jpg",
      price: 220,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.8,
      numReviews: 13,
      description: "high quality product",
      show: false,
    },
    {
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
      show: false,
    },
    {
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      show: false,
    },
    {
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
      show: true,
    },
  ],
};
module.exports = data;
